version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: B@123456m
      MYSQL_DATABASE: expensetracker
      MYSQL_USER: expensetracker-behrooz
      MYSQL_PASSWORD: B@31654m
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
